import '../entities/event.dart';
import '../repositories/event_repository.dart';

/// Use case for creating a new event
/// Orchestrates event creation with business rules
class CreateEventUseCase {
  final EventRepository _repository;

  CreateEventUseCase(this._repository);

  /// Execute event creation with validation
  Future<Event> execute({
    required String name,
    required String emoji,
    required String groupId,
    DateTime? startDateTime,
    DateTime? endDateTime,
    EventLocation? location,
  }) async {
    // Business rule: validate event name
    if (name.trim().isEmpty) {
      throw ArgumentError('Event name cannot be empty');
    }

    // Business rule: validate end time if provided
    if (startDateTime != null && endDateTime != null) {
      if (endDateTime.isBefore(startDateTime)) {
        throw ArgumentError('End time must be after start time');
      }
    }

    // Create event entity
    final event = Event(
      id: '', // Will be generated by repository
      name: name.trim(),
      emoji: emoji,
      groupId: groupId,
      startDateTime: startDateTime,
      endDateTime: endDateTime,
      location: location,
      status: EventStatus.pending,
      createdAt: DateTime.now(),
    );

    // Delegate to repository
    return await _repository.createEvent(event);
  }
}
