import '../../features/auth/data/models/country.dart';


final List<Country> countries = [
    Country(flag: '🇦🇱', name: 'Albania', code: '+355'),
    Country(flag: '🇦🇩', name: 'Andorra', code: '+376'),
    Country(flag: '🇦🇹', name: 'Austria', code: '+43'),
    Country(flag: '🇧🇾', name: 'Belarus', code: '+375'),
    Country(flag: '🇧🇪', name: 'Belgium', code: '+32'),
    Country(flag: '🇧🇦', name: 'Bosnia & Herzegovina', code: '+387'),
    Country(flag: '🇧🇬', name: 'Bulgaria', code: '+359'),
    Country(flag: '🇭🇷', name: 'Croatia', code: '+385'),
    Country(flag: '🇨🇾', name: 'Cyprus', code: '+357'),
    Country(flag: '🇨🇿', name: 'Czech Republic', code: '+420'),
    Country(flag: '🇩🇰', name: 'Denmark', code: '+45'),
    Country(flag: '🇪🇪', name: 'Estonia', code: '+372'),
    Country(flag: '🇫🇴', name: 'Faroe Islands', code: '+298'),
    Country(flag: '🇫🇮', name: 'Finland', code: '+358'),
    Country(flag: '🇫🇷', name: 'France', code: '+33'),
    Country(flag: '🇩🇪', name: 'Germany', code: '+49'),
    Country(flag: '🇬🇷', name: 'Greece', code: '+30'),
    Country(flag: '🇭🇺', name: 'Hungary', code: '+36'),
    Country(flag: '🇮🇸', name: 'Iceland', code: '+354'),
    Country(flag: '🇮🇪', name: 'Ireland', code: '+353'),
    Country(flag: '🇮🇹', name: 'Italy', code: '+39'),
    Country(flag: '🇽🇰', name: 'Kosovo', code: '+383'),
    Country(flag: '🇱🇻', name: 'Latvia', code: '+371'),
    Country(flag: '🇱🇮', name: 'Liechtenstein', code: '+423'),
    Country(flag: '🇱🇹', name: 'Lithuania', code: '+370'),
    Country(flag: '🇱🇺', name: 'Luxembourg', code: '+352'),
    Country(flag: '🇲🇹', name: 'Malta', code: '+356'),
    Country(flag: '🇲🇩', name: 'Moldova', code: '+373'),
    Country(flag: '🇲🇨', name: 'Monaco', code: '+377'),
    Country(flag: '🇲🇪', name: 'Montenegro', code: '+382'),
    Country(flag: '🇳🇱', name: 'Netherlands', code: '+31'),
    Country(flag: '🇲🇰', name: 'North Macedonia', code: '+389'),
    Country(flag: '🇳🇴', name: 'Norway', code: '+47'),
    Country(flag: '🇵🇱', name: 'Poland', code: '+48'),
    Country(flag: '🇵🇹', name: 'Portugal', code: '+351'),
    Country(flag: '🇷🇴', name: 'Romania', code: '+40'),
    Country(flag: '🇷🇺', name: 'Russia', code: '+7'),
    Country(flag: '🇸🇲', name: 'San Marino', code: '+378'),
    Country(flag: '🇷🇸', name: 'Serbia', code: '+381'),
    Country(flag: '🇸🇰', name: 'Slovakia', code: '+421'),
    Country(flag: '🇸🇮', name: 'Slovenia', code: '+386'),
    Country(flag: '🇪🇸', name: 'Spain', code: '+34'),
    Country(flag: '🇸🇪', name: 'Sweden', code: '+46'),
    Country(flag: '🇨🇭', name: 'Switzerland', code: '+41'),
    Country(flag: '🇺🇦', name: 'Ukraine', code: '+380'),
    Country(flag: '🇬🇧', name: 'United Kingdom', code: '+44'),
    Country(flag: '🇻🇦', name: 'Vatican City', code: '+379'),
  ];